### ISSUE TITLE
Latest version breaks chat formatting

### ISSUE THREAD

**Issue by jacobvd0** [hyperdefined/AnarchyStats#15]
![image](https://user-images.githubusercontent.com/46667568/175234301-a8d0d93e-5888-4c6c-b8ab-13c58da83e26.png)
I've tried using the § symbol too but that just produces a ton of errors.

**Comment by hyperdefined** [comment]
The latest version currently (1.5) uses MiniMessage for formatting instead of the usually color codes. Most plugins are converting over, including mine.

You can see how to use MiniMessage [here](https://docs.adventure.kyori.net/minimessage/format.html). If you have any questions, let me know!

**Comment by jacobvd0** [comment]
Ah, alright. Thanks for letting me know!
