### ISSUE TITLE
Plugin does not read world size correctly (0)

### ISSUE THREAD

**Issue by Leonardo-Fiori** [hyperdefined/AnarchyStats#3]
Always wanted a simple plugin like this :) 
Not just for anarchy servers, it's good for SMP too. 

Issue: does not read world size (says 0)

![image](https://user-images.githubusercontent.com/25549272/104444026-7f5a9e80-5597-11eb-930b-d8f78e15d815.png)

Tuinity version git-Tuinity-"8954b61" (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
AnarchyStats version 1.4

Additional suggestions: ability to change date format (Day/Month/Year), ability to change the command (had to define an alias for /info to /anarchystats:info in commands.yml because WorldGuard is overriding /info)

**Comment by hyperdefined** [comment]
What is your world file name? I hardcoded to look for the default `world`, `world_nether`, and `world_the_end` for the world size. If those aren't' your folder names then that's most likely why. I will change this in the next update so you can change them.

Thanks for the suggestions! I will be fixing these issues in the next update! I will most likely release it today :)

**Comment by Leonardo-Fiori** [comment]
> What is your world file name? I hardcoded to look for the default `world`, `world_nether`, and `world_the_end` for the world size. If those aren't' your folder names then that's most likely why. I will change this in the next update so you can change them.
> 
> Thanks for the suggestions! I will be fixing these issues in the next update! I will most likely release it today :)

Ohh! Well, hardcoded names, that's the explanation! 😄 
The name is "World" with a capital W. You may ask why. Well... 🤷‍♂️

**Comment by hyperdefined** [comment]
Perfect timing, I just released the new update to address these issues. You have to regenerate your config and edit it as fit.

https://github.com/hyperdefined/AnarchyStats/releases/tag/1.4.1

**Comment by Leonardo-Fiori** [comment]
Works perfectly, thanks! Small neat plugin :)

**Comment by hyperdefined** [comment]
Thanks for the feedback! I'm going to close this issue since it's resolved, but feel free to create a new one in the future if you have any problems.
