### ISSUE TITLE
Plugin disabled when change command

### ISSUE THREAD

**Issue by Leonardo-Fiori** [hyperdefined/AnarchyStats#4]
When I change the default command from info to "stats" the plugin won't get enabled on load 😄 
Test on latest Paper/Tunity

it-Tuinity-"1d169e7" (MC: 1.16.5)

**Comment by hyperdefined** [comment]
Can you post a server log? I can't tell what's going on otherwise.

**Comment by hyperdefined** [comment]
I fixed this issue in the latest update, [1.4.2](https://github.com/hyperdefined/AnarchyStats/releases/tag/1.4.2).
